# ---------------------------
# Docker Compose - Tikzok
# ---------------------------

version: "3.9"

services:

  # ---------------------------
  # PostgreSQL
  # ---------------------------
  db:
    image: postgres:15
    container_name: tikzok_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zabiullah123.
      POSTGRES_DB: tikzok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------------------------
  # Redis (OTP)
  # ---------------------------
  redis:
    image: redis:7
    container_name: tikzok_redis
    restart: always
    ports:
      - "6379:6379"

  # ---------------------------
  # Flask App
  # ---------------------------
  web:
    build: .
    container_name: tikzok_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:Zabiullah123.@db:5432/tikzok
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data: