services:

  web:
    build: .
    container_name: yeslek_app
    restart: always
    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: postgresql://postgres:Zabiullah123.@34.155.189.12:5432/yeslek
      REDIS_URL: rediss://default:AZmhAAIncDE4Zjk3YjcwOTllYTk0YzcwOWYwZWIxNzdjNWNkYWM3MHAxMzkzMjk@modern-basilisk-39329.upstash.io:6379

    volumes:
      - .:/app